---
- hosts: linked
  tasks:
    - name: Retrieve token links
      ansible.builtin.include_tasks: retrieve-tokens.yaml
- hosts: local
  collections:
    - skupper.network
  tasks:
    - ansible.builtin.import_role:
        name: skupper_init
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 1
    - ansible.builtin.import_role:
        name: skupper_token
      when: podman is not defined
    - name: Displaying generated tokens
      debug:
        msg: "Generated tokens -> {{ generatedToken }}"
      when: podman is not defined
    - name: Store token in vault
      community.hashi_vault.vault_write:
        url: "{{ vault_url }}"
        path: "skupper/{{ init['siteName'] }}"
        data:
          token: "{{ generatedToken }}"
      when: podman is not defined
    - ansible.builtin.import_role:
        name: skupper_link